/** División política del Ecuador: las 24 provincias y sus cantones.
 *
 *  Esto acaba impreso en una factura, así que aquí no se rellena «a ojo»: cada
 *  cantón está escrito con su nombre oficial y su tilde. La Concordia figura en
 *  Santo Domingo de los Tsáchilas, que es donde quedó tras zanjarse el litigio
 *  con Esmeraldas.
 *
 *  Vive en el frontend a propósito: el servidor guarda provincia y ciudad como
 *  texto libre (schemas/clientes.py) y no valida que una pertenezca a la otra,
 *  para no mantener el mismo catálogo en dos sitios. */
export const PROVINCIAS: Record<string, string[]> = {
  Azuay: [
    "Camilo Ponce Enríquez",
    "Chordeleg",
    "Cuenca",
    "El Pan",
    "Girón",
    "Guachapala",
    "Gualaceo",
    "Nabón",
    "Oña",
    "Paute",
    "Pucará",
    "San Fernando",
    "Santa Isabel",
    "Sevilla de Oro",
    "Sígsig",
  ],
  Bolívar: [
    "Caluma",
    "Chillanes",
    "Chimbo",
    "Echeandía",
    "Guaranda",
    "Las Naves",
    "San Miguel",
  ],
  Cañar: ["Azogues", "Biblián", "Cañar", "Déleg", "El Tambo", "La Troncal", "Suscal"],
  Carchi: ["Bolívar", "Espejo", "Mira", "Montúfar", "San Pedro de Huaca", "Tulcán"],
  Chimborazo: [
    "Alausí",
    "Chambo",
    "Chunchi",
    "Colta",
    "Cumandá",
    "Guamote",
    "Guano",
    "Pallatanga",
    "Penipe",
    "Riobamba",
  ],
  Cotopaxi: ["La Maná", "Latacunga", "Pangua", "Pujilí", "Salcedo", "Saquisilí", "Sigchos"],
  "El Oro": [
    "Arenillas",
    "Atahualpa",
    "Balsas",
    "Chilla",
    "El Guabo",
    "Huaquillas",
    "Las Lajas",
    "Machala",
    "Marcabelí",
    "Pasaje",
    "Piñas",
    "Portovelo",
    "Santa Rosa",
    "Zaruma",
  ],
  Esmeraldas: [
    "Atacames",
    "Eloy Alfaro",
    "Esmeraldas",
    "Muisne",
    "Quinindé",
    "Rioverde",
    "San Lorenzo",
  ],
  Galápagos: ["Isabela", "San Cristóbal", "Santa Cruz"],
  Guayas: [
    "Alfredo Baquerizo Moreno",
    "Balao",
    "Balzar",
    "Colimes",
    "Coronel Marcelino Maridueña",
    "Daule",
    "Durán",
    "El Empalme",
    "El Triunfo",
    "General Antonio Elizalde",
    "Guayaquil",
    "Isidro Ayora",
    "Lomas de Sargentillo",
    "Milagro",
    "Naranjal",
    "Naranjito",
    "Nobol",
    "Palestina",
    "Pedro Carbo",
    "Playas",
    "Salitre",
    "Samborondón",
    "San Jacinto de Yaguachi",
    "Santa Lucía",
    "Simón Bolívar",
  ],
  Imbabura: [
    "Antonio Ante",
    "Cotacachi",
    "Ibarra",
    "Otavalo",
    "Pimampiro",
    "San Miguel de Urcuquí",
  ],
  Loja: [
    "Calvas",
    "Catamayo",
    "Celica",
    "Chaguarpamba",
    "Espíndola",
    "Gonzanamá",
    "Loja",
    "Macará",
    "Olmedo",
    "Paltas",
    "Pindal",
    "Puyango",
    "Quilanga",
    "Saraguro",
    "Sozoranga",
    "Zapotillo",
  ],
  "Los Ríos": [
    "Baba",
    "Babahoyo",
    "Buena Fe",
    "Mocache",
    "Montalvo",
    "Palenque",
    "Puebloviejo",
    "Quevedo",
    "Quinsaloma",
    "Urdaneta",
    "Valencia",
    "Ventanas",
    "Vinces",
  ],
  Manabí: [
    "24 de Mayo",
    "Bolívar",
    "Chone",
    "El Carmen",
    "Flavio Alfaro",
    "Jama",
    "Jaramijó",
    "Jipijapa",
    "Junín",
    "Manta",
    "Montecristi",
    "Olmedo",
    "Paján",
    "Pedernales",
    "Pichincha",
    "Portoviejo",
    "Puerto López",
    "Rocafuerte",
    "San Vicente",
    "Santa Ana",
    "Sucre",
    "Tosagua",
  ],
  "Morona Santiago": [
    "Gualaquiza",
    "Huamboya",
    "Limón Indanza",
    "Logroño",
    "Morona",
    "Pablo Sexto",
    "Palora",
    "San Juan Bosco",
    "Santiago",
    "Sucúa",
    "Taisha",
    "Tiwintza",
  ],
  Napo: ["Archidona", "Carlos Julio Arosemena Tola", "El Chaco", "Quijos", "Tena"],
  Orellana: ["Aguarico", "Francisco de Orellana", "La Joya de los Sachas", "Loreto"],
  Pastaza: ["Arajuno", "Mera", "Pastaza", "Santa Clara"],
  Pichincha: [
    "Cayambe",
    "Mejía",
    "Pedro Moncayo",
    "Pedro Vicente Maldonado",
    "Puerto Quito",
    "Quito",
    "Rumiñahui",
    "San Miguel de los Bancos",
  ],
  "Santa Elena": ["La Libertad", "Salinas", "Santa Elena"],
  "Santo Domingo de los Tsáchilas": ["La Concordia", "Santo Domingo"],
  Sucumbíos: [
    "Cascales",
    "Cuyabeno",
    "Gonzalo Pizarro",
    "Lago Agrio",
    "Putumayo",
    "Shushufindi",
    "Sucumbíos",
  ],
  Tungurahua: [
    "Ambato",
    "Baños de Agua Santa",
    "Cevallos",
    "Mocha",
    "Patate",
    "Quero",
    "San Pedro de Pelileo",
    "Santiago de Píllaro",
    "Tisaleo",
  ],
  "Zamora Chinchipe": [
    "Centinela del Cóndor",
    "Chinchipe",
    "El Pangui",
    "Nangaritza",
    "Palanda",
    "Paquisha",
    "Yacuambi",
    "Yantzaza",
    "Zamora",
  ],
};

export const NOMBRES_PROVINCIAS = Object.keys(PROVINCIAS);
