"""nucleo

Revision ID: 0001
Revises: 
Create Date: 2026-08-24 22:36:29.727303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('actor_rol', sa.String(length=20), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('accion', sa.String(length=40), nullable=False),
    sa.Column('tabla', sa.String(length=80), nullable=True),
    sa.Column('registro_id', sa.String(length=64), nullable=True),
    sa.Column('antes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('despues', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('request_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_actor_user_id'), 'audit_log', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_tenant_id'), 'audit_log', ['tenant_id'], unique=False)
    op.create_table('cost_rates',
    sa.Column('proveedor', sa.String(length=50), nullable=False),
    sa.Column('concepto', sa.String(length=120), nullable=False),
    sa.Column('costo_unitario', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('unidad', sa.String(length=50), nullable=False),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('vigente_desde', sa.Date(), nullable=False),
    sa.Column('vigente_hasta', sa.Date(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cost_rates'))
    )
    op.create_table('planes',
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('precio_mensual', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('limites', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('vigente_desde', sa.Date(), nullable=False),
    sa.Column('vigente_hasta', sa.Date(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_planes')),
    sa.UniqueConstraint('codigo', 'vigente_desde', name=op.f('uq_planes_codigo_vigente_desde'))
    )
    op.create_index(op.f('ix_planes_codigo'), 'planes', ['codigo'], unique=False)
    op.create_table('promo_codes',
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tipo', sa.Enum('PORCENTAJE', 'MONTO_FIJO', 'PRECIO_FIJO', name='tipo_promo'), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_usos', sa.Integer(), nullable=True),
    sa.Column('usos', sa.Integer(), nullable=False),
    sa.Column('vigente_desde', sa.Date(), nullable=False),
    sa.Column('vigente_hasta', sa.Date(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promo_codes')),
    sa.UniqueConstraint('codigo', name=op.f('uq_promo_codes_codigo'))
    )
    op.create_table('tenants',
    sa.Column('ruc', sa.String(length=13), nullable=False),
    sa.Column('razon_social', sa.String(length=300), nullable=False),
    sa.Column('nombre_comercial', sa.String(length=300), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('direccion_matriz', sa.Text(), nullable=True),
    sa.Column('estado', sa.Enum('ACTIVO', 'SUSPENDIDO', 'BAJA', name='estado_tenant'), nullable=False),
    sa.Column('ambiente_sri', sa.Enum('PRUEBAS', 'PRODUCCION', name='ambiente_sri'), nullable=False),
    sa.Column('obligado_contabilidad', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants')),
    sa.UniqueConstraint('ruc', name=op.f('uq_tenants_ruc'))
    )
    op.create_table('buzon_correos',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.String(length=300), nullable=False),
    sa.Column('remitente', sa.String(length=320), nullable=True),
    sa.Column('asunto', sa.String(length=500), nullable=True),
    sa.Column('xml_sha256', sa.String(length=64), nullable=True),
    sa.Column('tipo_detectado', sa.String(length=30), nullable=True),
    sa.Column('estado', sa.Enum('RECIBIDO', 'PARSEADO', 'DUPLICADO', 'ERROR', name='estado_correo_buzon'), nullable=False),
    sa.Column('payload_path', sa.String(length=500), nullable=True),
    sa.Column('recibido_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('procesado_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_buzon_correos_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_buzon_correos')),
    sa.UniqueConstraint('message_id', name=op.f('uq_buzon_correos_message_id'))
    )
    op.create_index(op.f('ix_buzon_correos_tenant_id'), 'buzon_correos', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_buzon_correos_xml_sha256'), 'buzon_correos', ['xml_sha256'], unique=False)
    op.create_table('clientes_finales',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('tipo_identificacion', sa.Enum('RUC', 'CEDULA', 'PASAPORTE', 'CONSUMIDOR_FINAL', 'ID_EXTERIOR', name='tipo_identificacion'), nullable=False),
    sa.Column('identificacion', sa.String(length=20), nullable=False),
    sa.Column('razon_social', sa.String(length=300), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_clientes_finales_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clientes_finales')),
    sa.UniqueConstraint('tenant_id', 'tipo_identificacion', 'identificacion', name=op.f('uq_clientes_finales_tenant_id_tipo_identificacion_identificacion'))
    )
    op.create_index(op.f('ix_clientes_finales_tenant_id'), 'clientes_finales', ['tenant_id'], unique=False)
    op.create_table('establecimientos',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=3), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=True),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_establecimientos_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_establecimientos')),
    sa.UniqueConstraint('tenant_id', 'codigo', name=op.f('uq_establecimientos_tenant_id_codigo'))
    )
    op.create_index(op.f('ix_establecimientos_tenant_id'), 'establecimientos', ['tenant_id'], unique=False)
    op.create_table('productos',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=300), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tipo', sa.Enum('BIEN', 'SERVICIO', name='tipo_producto'), nullable=False),
    sa.Column('precio_sin_iva', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('codigo_iva', sa.String(length=2), nullable=False),
    sa.Column('porcentaje_iva', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('maneja_inventario', sa.Boolean(), nullable=False),
    sa.Column('stock', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stock_minimo', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('mostrar_en_tienda', sa.Boolean(), nullable=False),
    sa.Column('imagen_url', sa.String(length=500), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_productos_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_productos')),
    sa.UniqueConstraint('tenant_id', 'codigo', name=op.f('uq_productos_tenant_id_codigo'))
    )
    op.create_index(op.f('ix_productos_tenant_id'), 'productos', ['tenant_id'], unique=False)
    op.create_table('promo_uses',
    sa.Column('promo_code_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('monto_descuento', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('retenido', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('usado_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['promo_code_id'], ['promo_codes.id'], name=op.f('fk_promo_uses_promo_code_id_promo_codes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_promo_uses_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promo_uses'))
    )
    op.create_index(op.f('ix_promo_uses_promo_code_id'), 'promo_uses', ['promo_code_id'], unique=False)
    op.create_index(op.f('ix_promo_uses_tenant_id'), 'promo_uses', ['tenant_id'], unique=False)
    op.create_table('suscripciones',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('estado', sa.Enum('ACTIVA', 'MOROSA', 'SUSPENDIDA', 'CANCELADA', name='estado_suscripcion'), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('inicia', sa.Date(), nullable=False),
    sa.Column('termina', sa.Date(), nullable=True),
    sa.Column('proximo_cobro', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['planes.id'], name=op.f('fk_suscripciones_plan_id_planes')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_suscripciones_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suscripciones'))
    )
    op.create_index(op.f('ix_suscripciones_tenant_id'), 'suscripciones', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.Column('rol', sa.Enum('CLIENTE', 'SUPERADMIN', 'SOPORTE', 'LECTURA', name='rol_usuario'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('totp_secret_enc', sa.String(length=500), nullable=True),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('lockout_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_users_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('whatsapp_msgs',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('wa_phone', sa.String(length=20), nullable=False),
    sa.Column('direccion', sa.Enum('ENTRANTE', 'SALIENTE', name='direccion_msg'), nullable=False),
    sa.Column('categoria', sa.Enum('EMPRESA', 'USUARIO', 'SERVICIO', name='categoria_msg'), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('wa_message_id', sa.String(length=128), nullable=True),
    sa.Column('contenido', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('costo', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_whatsapp_msgs_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_whatsapp_msgs')),
    sa.UniqueConstraint('wa_message_id', name=op.f('uq_whatsapp_msgs_wa_message_id'))
    )
    op.create_index(op.f('ix_whatsapp_msgs_created_at'), 'whatsapp_msgs', ['created_at'], unique=False)
    op.create_index(op.f('ix_whatsapp_msgs_tenant_id'), 'whatsapp_msgs', ['tenant_id'], unique=False)
    op.create_table('comprobantes',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('FACTURA', 'LIQUIDACION_COMPRA', 'NOTA_CREDITO', 'NOTA_DEBITO', 'GUIA_REMISION', 'RETENCION', name='tipo_comprobante'), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'FIRMADO', 'ENVIADO_SRI', 'AUTORIZADO', 'RECHAZADO', 'DEVUELTO', name='estado_comprobante'), nullable=False),
    sa.Column('ambiente', sa.Enum('PRUEBAS', 'PRODUCCION', name='ambiente_sri'), nullable=False),
    sa.Column('establecimiento', sa.String(length=3), nullable=False),
    sa.Column('punto_emision', sa.String(length=3), nullable=False),
    sa.Column('secuencial', sa.Integer(), nullable=False),
    sa.Column('clave_acceso', sa.String(length=49), nullable=True),
    sa.Column('cliente_final_id', sa.UUID(), nullable=True),
    sa.Column('fecha_emision', sa.Date(), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('iva', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('origen', sa.String(length=20), nullable=False),
    sa.Column('xml_path', sa.String(length=500), nullable=True),
    sa.Column('ride_path', sa.String(length=500), nullable=True),
    sa.Column('sha256_xml', sa.String(length=64), nullable=True),
    sa.Column('sri_mensajes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('autorizado_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_final_id'], ['clientes_finales.id'], name=op.f('fk_comprobantes_cliente_final_id_clientes_finales'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_comprobantes_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comprobantes')),
    sa.UniqueConstraint('clave_acceso', name=op.f('uq_comprobantes_clave_acceso')),
    sa.UniqueConstraint('tenant_id', 'tipo', 'establecimiento', 'punto_emision', 'secuencial', name=op.f('uq_comprobantes_tenant_id_tipo_establecimiento_punto_emision_secuencial'))
    )
    op.create_index(op.f('ix_comprobantes_estado'), 'comprobantes', ['estado'], unique=False)
    op.create_index(op.f('ix_comprobantes_tenant_id'), 'comprobantes', ['tenant_id'], unique=False)
    op.create_table('notas_internas',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('autor_user_id', sa.UUID(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['autor_user_id'], ['users.id'], name=op.f('fk_notas_internas_autor_user_id_users')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_notas_internas_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notas_internas'))
    )
    op.create_index(op.f('ix_notas_internas_tenant_id'), 'notas_internas', ['tenant_id'], unique=False)
    op.create_table('pagos',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('suscripcion_id', sa.UUID(), nullable=True),
    sa.Column('concepto', sa.String(length=300), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('metodo', sa.Enum('TRANSFERENCIA', 'PAYPHONE', 'EFECTIVO', 'OTRO', name='metodo_pago'), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'CONFIRMADO', 'RECHAZADO', name='estado_pago'), nullable=False),
    sa.Column('referencia', sa.String(length=200), nullable=True),
    sa.Column('comprobante_url', sa.String(length=500), nullable=True),
    sa.Column('vence_at', sa.Date(), nullable=True),
    sa.Column('pagado_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['suscripcion_id'], ['suscripciones.id'], name=op.f('fk_pagos_suscripcion_id_suscripciones')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_pagos_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pagos'))
    )
    op.create_index(op.f('ix_pagos_tenant_id'), 'pagos', ['tenant_id'], unique=False)
    op.create_table('secuenciales',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('establecimiento_id', sa.UUID(), nullable=False),
    sa.Column('punto_emision', sa.String(length=3), nullable=False),
    sa.Column('tipo_comprobante', sa.String(length=30), nullable=False),
    sa.Column('secuencial_actual', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['establecimiento_id'], ['establecimientos.id'], name=op.f('fk_secuenciales_establecimiento_id_establecimientos'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_secuenciales_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_secuenciales')),
    sa.UniqueConstraint('tenant_id', 'establecimiento_id', 'punto_emision', 'tipo_comprobante', name=op.f('uq_secuenciales_tenant_id_establecimiento_id_punto_emision_tipo_comprobante'))
    )
    op.create_index(op.f('ix_secuenciales_tenant_id'), 'secuenciales', ['tenant_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rotated_to', sa.UUID(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_user_sessions_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_user_sessions_token_hash'))
    )
    op.create_index(op.f('ix_user_sessions_tenant_id'), 'user_sessions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_table('recargas',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pago_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pago_id'], ['pagos.id'], name=op.f('fk_recargas_pago_id_pagos')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_recargas_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recargas'))
    )
    op.create_index(op.f('ix_recargas_tenant_id'), 'recargas', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recargas_tenant_id'), table_name='recargas')
    op.drop_table('recargas')
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_tenant_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_secuenciales_tenant_id'), table_name='secuenciales')
    op.drop_table('secuenciales')
    op.drop_index(op.f('ix_pagos_tenant_id'), table_name='pagos')
    op.drop_table('pagos')
    op.drop_index(op.f('ix_notas_internas_tenant_id'), table_name='notas_internas')
    op.drop_table('notas_internas')
    op.drop_index(op.f('ix_comprobantes_tenant_id'), table_name='comprobantes')
    op.drop_index(op.f('ix_comprobantes_estado'), table_name='comprobantes')
    op.drop_table('comprobantes')
    op.drop_index(op.f('ix_whatsapp_msgs_tenant_id'), table_name='whatsapp_msgs')
    op.drop_index(op.f('ix_whatsapp_msgs_created_at'), table_name='whatsapp_msgs')
    op.drop_table('whatsapp_msgs')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_suscripciones_tenant_id'), table_name='suscripciones')
    op.drop_table('suscripciones')
    op.drop_index(op.f('ix_promo_uses_tenant_id'), table_name='promo_uses')
    op.drop_index(op.f('ix_promo_uses_promo_code_id'), table_name='promo_uses')
    op.drop_table('promo_uses')
    op.drop_index(op.f('ix_productos_tenant_id'), table_name='productos')
    op.drop_table('productos')
    op.drop_index(op.f('ix_establecimientos_tenant_id'), table_name='establecimientos')
    op.drop_table('establecimientos')
    op.drop_index(op.f('ix_clientes_finales_tenant_id'), table_name='clientes_finales')
    op.drop_table('clientes_finales')
    op.drop_index(op.f('ix_buzon_correos_xml_sha256'), table_name='buzon_correos')
    op.drop_index(op.f('ix_buzon_correos_tenant_id'), table_name='buzon_correos')
    op.drop_table('buzon_correos')
    op.drop_table('tenants')
    op.drop_table('promo_codes')
    op.drop_index(op.f('ix_planes_codigo'), table_name='planes')
    op.drop_table('planes')
    op.drop_table('cost_rates')
    op.drop_index(op.f('ix_audit_log_tenant_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_user_id'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
    # Alembic no elimina los tipos ENUM al borrar las tablas: sin esto, un
    # ciclo downgrade→upgrade falla con "type already exists".
    for enum_name in (
        'estado_tenant', 'ambiente_sri', 'rol_usuario', 'estado_suscripcion',
        'tipo_comprobante', 'estado_comprobante', 'tipo_identificacion', 'tipo_producto',
        'metodo_pago', 'estado_pago', 'tipo_promo', 'direccion_msg', 'categoria_msg',
        'estado_correo_buzon',
    ):
        op.execute(f'DROP TYPE IF EXISTS {enum_name}')
